databases:
  - name: budget_app
    databaseName: db_budget_app_syke
    user: budget_app

services:
  - type: web
    name: budget_app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db_budget_app_syke
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false